# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-07 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200507_2146'),
    ]

    operations = [
    ]
