# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-07 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200507_2242'),
    ]

    operations = [
    ]
