# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-10 14:36
from __future__ import unicode_literals

from django.db import migrations
import re


def forwards(apps, schema_editor):
    regex = re.compile('[+?\d+]')
    UserInfoModel = apps.get_model('users', 'UserInfo')

    queryset = UserInfoModel.objects.all()
    ### iterate through models and skip duplicate
    for obj in queryset:
        res = ''
        res = res.join(regex.findall(obj.phone))
        if len(res) == 0:
            continue

        if res[0] == '8':
            res = '+7'+res[1:]
        obj.phone = res
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200507_2309'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
    ]
