# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-23 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200511_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email_valid',
            field=models.NullBooleanField(default=False),
        ),
    ]
