# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-23 13:05
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    UserInfoModel = apps.get_model('users', 'UserInfo')

    queryset = UserInfoModel.objects.all()
    ### iterate through models and skip duplicate
    for obj in queryset:
        obj.email_valid = True
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userinfo_email_valid'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
    ]
