# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-23 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userinfo_email_valid'),
    ]

    operations = [
    ]
