# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-29 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200523_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email_temp',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email_validation_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='validating_email',
            field=models.NullBooleanField(default=False),
        ),
    ]
