# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-20 21:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_auto_20200120_1843'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schoolform', '0020_auto_20191222_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('is_percent', models.NullBooleanField(default=False)),
                ('elapsed_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfCodes', to=settings.AUTH_USER_MODEL)),
                ('evticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventTicketTemplate')),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolform.SchoolAppFlow')),
                ('price', models.ManyToManyField(blank=True, null=True, to='schoolform.PriceField')),
                ('referal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refCodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
