# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-21 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200120_2201'),
        ('promocode', '0003_promocode_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='evticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventTicketTemplate'),
        ),
    ]
