# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-02-06 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0004_promocode_evticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='services',
            field=models.NullBooleanField(default=False),
        ),
    ]
