# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-20 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0012_schoolpublicpage'),
        ('django_tinkoff_merchant', '0004_auto_20191005_0630'),
        ('schoolform', '0020_auto_20191222_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTicketTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=250)),
                ('ticket_cnt', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('per_user_cnt', models.PositiveSmallIntegerField()),
                ('solded_cnt', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('address_url', models.URLField()),
                ('ticket_sale_start', models.DateTimeField()),
                ('ticket_sale_stop', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('toss', models.ManyToManyField(blank=True, null=True, related_name='_offlineevent_toss_+', to='blog.TermsOfServicePage')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('owner_firstname', models.CharField(max_length=40)),
                ('owner_secondname', models.CharField(max_length=40)),
                ('owner_middlename', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('price', models.PositiveIntegerField(default=0)),
                ('accepted_toss', models.ManyToManyField(to='blog.TermsOfServicePage')),
                ('eventticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventTicketTemplate')),
                ('payment', models.ManyToManyField(blank=True, null=True, related_name='ticket', to='django_tinkoff_merchant.Payment', verbose_name='Payment')),
                ('price_f', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolform.PriceField')),
            ],
        ),
        migrations.AddField(
            model_name='eventtickettemplate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.OfflineEvent'),
        ),
    ]
