# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-20 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineevent',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='offlineevent',
            name='address_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='offlineevent',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='offlineevent',
            name='ticket_sale_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='offlineevent',
            name='ticket_sale_stop',
            field=models.DateTimeField(null=True),
        ),
    ]
