# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-20 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200120_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='owner_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='owner_middlename',
            new_name='middlename',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='owner_secondname',
            new_name='secondname',
        ),
    ]
