# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-20 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200120_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
