# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-25 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200120_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pay_url_sended',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_sended',
            field=models.NullBooleanField(default=False),
        ),
    ]
