# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-23 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200125_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='phone_valid',
            field=models.NullBooleanField(default=False),
        ),
    ]
