# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-07 22:59
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    


    TicketModel = apps.get_model('events', 'Ticket')
   
    queryset = TicketModel.objects.all()

    for obj in queryset:
        obj.email = obj.email.lower()
        obj.save()

  
class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_ticket_phone_valid'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
    ]
