# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-07 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_ticket_phone_valid'),
    ]

    operations = [
    ]
