# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-24 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200524_1600'),
    ]

    operations = [
    ]
