# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-03-17 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinkoff_merchant', '0005_tinkoffsettings_name'),
        ('events', '0011_ticket_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineevent',
            name='terminal',
            field=models.ManyToManyField(blank=True, related_name='_offlineevent_terminal_+', to='django_tinkoff_merchant.TinkoffSettings'),
        ),
    ]
