# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-29 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(editable=False, verbose_name='The amount in cents')),
                ('order_id', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Order number')),
                ('description', models.TextField(blank=True, default='', editable=False, max_length=250, verbose_name='Description')),
                ('success', models.BooleanField(default=False, editable=False, verbose_name='Successfully completed')),
                ('status', models.CharField(default='', editable=False, max_length=20, verbose_name='Transaction status')),
                ('payment_id', models.CharField(default='', editable=False, max_length=20, verbose_name='Unique identifier of the transaction in the Bank system')),
                ('error_code', models.CharField(default='', editable=False, max_length=20, verbose_name='Error code')),
                ('payment_url', models.CharField(blank=True, default='', editable=False, help_text='Link to the payment page. By default, the link is available within 24 hours.', max_length=100, verbose_name='Link to the payment page.')),
                ('message', models.TextField(blank=True, default='', editable=False, verbose_name='Brief description of the error')),
                ('details', models.TextField(blank=True, default='', editable=False, verbose_name='Detailed description of the error')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'verbose_name': 'Transaction',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, verbose_name='E-mail address to send the check to the buyer')),
                ('phone', models.CharField(blank=True, default='', max_length=64, verbose_name='Customer phone')),
                ('taxation', models.CharField(choices=[('osn', 'общая СН'), ('usn_income', 'упрощенная СН (доходы)'), ('usn_income_outcome', 'упрощенная СН (доходы минус расходы)'), ('envd', 'единый налог на вмененный доход'), ('esn', 'единый сельскохозяйственный налог'), ('patent', 'патентная СН')], max_length=20, verbose_name='Taxation system')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_tinkoff_merchant.Payment', verbose_name='Payment')),
            ],
            options={
                'verbose_name_plural': 'Check data',
                'verbose_name': 'Check details',
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of goods')),
                ('price', models.IntegerField(verbose_name='Price in cents')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='Quantity/weight')),
                ('amount', models.IntegerField(verbose_name='The amount of cents')),
                ('tax', models.CharField(choices=[('none', 'без НДС'), ('vat0', 'НДС по ставке 0%'), ('vat10', 'НДС чека по ставке 10%'), ('vat18', 'НДС чека по ставке 18%'), ('vat110', 'НДС чека по расчетной ставке 10/110'), ('vat118', 'НДС чека по расчетной ставке 18/118')], max_length=10, verbose_name='Tax rate')),
                ('ean13', models.CharField(blank=True, default='', max_length=20, verbose_name='Barcode')),
                ('shop_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Store code')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_tinkoff_merchant.Receipt', verbose_name='Check')),
            ],
            options={
                'verbose_name_plural': 'Product information',
                'verbose_name': 'Product information',
            },
        ),
    ]
