# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-03 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinkoff_merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinkoffSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.CharField(max_length=40, verbose_name='Номер терминала')),
                ('terminal_key', models.CharField(max_length=40, verbose_name='Пароль терминала')),
                ('using_school', models.BooleanField(default=False, verbose_name='Для школы')),
                ('using_services', models.BooleanField(default=False, verbose_name='Для услуг')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_tinkoff_merchant.TinkoffSettings', verbose_name='Терминал'),
        ),
    ]
