# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-04 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinkoff_merchant', '0002_auto_20191003_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
