# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-05 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinkoff_merchant', '0003_auto_20191004_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='order_obj',
            field=models.CharField(default='unknw', max_length=100, verbose_name='Номер услуги'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_plural',
            field=models.CharField(default='unknw', max_length=100, verbose_name='Название услуги'),
        ),
    ]
