# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-01 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinkoff_merchant', '0004_auto_20191005_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinkoffsettings',
            name='name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Название терминала'),
        ),
    ]
