# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-26 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolform', '0039_schoolscanfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('descr', models.TextField(blank=True)),
                ('time_start', models.DateTimeField()),
                ('has_homework', models.BooleanField(default=False)),
                ('homework_html', models.TextField(blank=True)),
                ('lesson_content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('curators', models.ManyToManyField(related_name='active_training', to='schoolform.SchoolAppCurator')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='schoolform.SchoolAppFlow')),
            ],
        ),
        migrations.AddField(
            model_name='schoollesson',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.SchoolTraining'),
        ),
    ]
