# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-30 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooltraining',
            name='curators',
            field=models.ManyToManyField(blank=True, related_name='active_training', to='schoolform.SchoolAppCurator'),
        ),
    ]
