# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-30 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20201230_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollesson',
            name='time_start',
            field=models.DateTimeField(blank=True),
        ),
    ]
