# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-24 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190823_1203'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritesPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favs', to='blog.PostPage')),
                ('users', models.ManyToManyField(related_name='fav_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
