# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-15 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentblogthread_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cnt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
