# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-24 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20190819_2008'),
        ('comments', '0004_auto_20190819_0753'),
    ]

    operations = [
    ]
