# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-04 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190731_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='code_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
