# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-22 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190804_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='phone',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
