# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-09-19 06:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_apporder_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apporder',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='apporder',
            name='slug',
        ),
        migrations.AddField(
            model_name='apporder',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serv_appl_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apporder',
            name='doer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serv_appl_doer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
