# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-09-19 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_apporder_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appresultfile',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to='app.AppOrder'),
        ),
    ]
