# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-09-20 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200919_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAutoGeneratorOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_login', models.URLField()),
                ('url_getDesc', models.URLField()),
                ('username', models.CharField(max_length=200)),
                ('userpass', models.CharField(max_length=200)),
                ('templateid', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
