# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-09-20 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200920_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='apporder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
