# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-09-23 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_apporder_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='apporder',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
