# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-09-28 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_apporder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appautogeneratoroptions',
            name='serv_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
