# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-08 10:35
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_apporder_workstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppExpertUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(blank=True, max_length=200, null=True)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('percent', models.PositiveSmallIntegerField(default=70)),
                ('slug', models.SlugField()),
                ('active', models.BooleanField(default=False)),
                ('orders_in_work', models.PositiveIntegerField(default=0)),
                ('workstate', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='expert_rec', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
