# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-23 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_appexpertuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='apporder',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Private Comments'),
        ),
    ]
