# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-02-06 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0046_schoolextendaccessservice_payed'),
        ('app', '0018_auto_20210206_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='apporder',
            name='price_f',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolform.PriceField'),
        ),
    ]
