# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-15 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
        ('blog', '0004_auto_20190709_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.PositiveIntegerField(default=0)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comments.Comment')),
                ('likes', models.ManyToManyField(related_name='liked_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.PositiveIntegerField(default=0)),
                ('likes', models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.PostPage')),
            ],
        ),
        migrations.CreateModel(
            name='LikeReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.PositiveIntegerField(default=0)),
                ('likes', models.ManyToManyField(related_name='liked_reply', to=settings.AUTH_USER_MODEL)),
                ('reply', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comments.CommentReply')),
            ],
        ),
    ]
