# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-08 18:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('price', models.PositiveIntegerField(blank=True)),
                ('expert', models.BooleanField()),
                ('date_cnt', wagtail.core.fields.RichTextField(blank=True)),
                ('date', models.DateTimeField(default=datetime.datetime.today, verbose_name='Service Added')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
