# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-08 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_servicepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='date_cnt',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
