# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-09 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190708_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepage',
            old_name='description',
            new_name='descr',
        ),
    ]
