# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-23 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_termsofservicepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='related_tos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.TermsOfServicePage', verbose_name='Соглашения и договора'),
        ),
    ]
