# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-23 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_servicepage_related_tos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='related_tos',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='related_tos',
            field=models.ManyToManyField(blank=True, null=True, related_name='_servicepage_related_tos_+', to='blog.TermsOfServicePage', verbose_name='Соглашения и договора'),
        ),
    ]
