# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-23 11:53
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190823_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='related_tos',
        ),
        migrations.AddField(
            model_name='termsofservicepage',
            name='services',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tos', to='blog.ServicePage', verbose_name='Соглашения и договора'),
        ),
    ]
