# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-23 12:03
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190823_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsofservicepage',
            name='services',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='toss',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, null=True, related_name='related_services', to='blog.TermsOfServicePage', verbose_name='Соглашения и договора'),
        ),
    ]
