# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-13 05:23
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190823_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='short_descr',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
