# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-01 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_schoolpublicpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='adult_cnt',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Взрослых в разборе'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='comp_parent',
            field=models.NullBooleanField(default=False, verbose_name='Совместимость родителей'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='impr_chld',
            field=models.NullBooleanField(default=False, verbose_name='Влияние на ребёнка'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='kids_cnt',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Детей в разборе'),
        ),
    ]
