# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-26 18:26
from __future__ import unicode_literals

import blog.models
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200818_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='descr',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='short_descr',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='about',
            field=wagtail.core.fields.StreamField([('about', wagtail.core.blocks.ListBlock(blog.models.ServiceAboutBlock, template='blocks/feedbackvideo_list.html'))], blank=True, null=True),
        ),
    ]
