# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-09-06 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_obj', models.CharField(default='None', max_length=100, verbose_name='Номер услуги/анкеты')),
                ('order_type', models.CharField(default='None', max_length=100, verbose_name='Название услуги')),
                ('tcb_id', models.CharField(blank=True, max_length=250, verbose_name='ID заявки в TCB')),
                ('link_url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на заявку в TCB')),
                ('status', models.CharField(blank=True, max_length=40, verbose_name='Текущий статус заявки')),
                ('created_at', models.DateTimeField(blank=True, verbose_name='Дата и время создания заявки.')),
                ('demo', models.NullBooleanField(verbose_name='Демо или реальная заявка')),
                ('committed', models.NullBooleanField(verbose_name='Подтверждена ли заявка')),
                ('first_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='Первый платеж')),
                ('order_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Сумма заказа')),
                ('product', models.CharField(blank=True, max_length=100, verbose_name='Тип продукта')),
                ('loan_number', models.CharField(blank=True, max_length=255, verbose_name='Номер договора')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя клиента')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия клиента')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество клиента')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Номер телефона')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('signing_type', models.CharField(blank=True, max_length=20, verbose_name='Тип подписания')),
            ],
        ),
        migrations.CreateModel(
            name='CreditApplicationItemsArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tinkoff_credit.CreditApplication', verbose_name='Список товаров')),
            ],
        ),
        migrations.CreateModel(
            name='CreditApplicationItemsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название товара')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Стоимость')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория товара')),
                ('vendorCode', models.CharField(blank=True, max_length=100, verbose_name='Артикул')),
                ('array', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinkoff_credit.CreditApplicationItemsArray', verbose_name='Товар')),
            ],
        ),
        migrations.CreateModel(
            name='TinkoffCreditSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopId', models.CharField(max_length=250, verbose_name='Shop identifier')),
                ('showcaseid', models.CharField(blank=True, max_length=250, null=True, verbose_name='Site identifier')),
                ('serverips', models.CharField(default='91.194.226.00/23', max_length=18, verbose_name='Tinkoff Servers netmask')),
                ('promoCode', models.CharField(max_length=100, verbose_name='Идентификатор кредитного продукта')),
            ],
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tinkoff_credit.TinkoffCreditSettings', verbose_name='Настройки'),
        ),
    ]
