# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-09-06 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplication',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время создания заявки.'),
        ),
    ]
