# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-09-06 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_credit', '0002_auto_20210906_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplication',
            name='first_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Первый платеж'),
        ),
        migrations.AlterField(
            model_name='creditapplication',
            name='order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Сумма заказа'),
        ),
    ]
