# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-09-06 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_credit', '0003_auto_20210906_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplicationitemsitem',
            name='array',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='array', to='tinkoff_credit.CreditApplicationItemsArray', verbose_name='Товар'),
        ),
    ]
