# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-09-06 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0049_randommail'),
        ('tinkoff_credit', '0004_auto_20210906_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='schoolappform',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='credit', to='schoolform.SchoolAppForm', verbose_name='Школьная анкета'),
        ),
    ]
