# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-09-06 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff_credit', '0005_creditapplication_schoolappform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplication',
            name='link_url',
            field=models.TextField(blank=True, verbose_name='Ссылка на заявку в TCB'),
        ),
    ]
