# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-23 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_tinkoff_merchant', '0004_auto_20191005_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('payed', models.NullBooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('percent', models.PositiveSmallIntegerField(default=70)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='serviceclient',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='service.ServiceExpert'),
        ),
        migrations.AddField(
            model_name='serviceclient',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_client', to='django_tinkoff_merchant.Payment', verbose_name='Payment'),
        ),
    ]
