# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-24 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_servicepage_short_descr'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceToss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toss', models.ManyToManyField(blank=True, null=True, to='blog.TermsOfServicePage')),
            ],
        ),
    ]
