# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-24 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_servicepage_short_descr'),
        ('service', '0002_servicetoss'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceclient',
            name='accepted_toss',
            field=models.ManyToManyField(blank=True, null=True, to='blog.TermsOfServicePage'),
        ),
    ]
