# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-24 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_serviceclient_accepted_toss'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceclient',
            name='created_by',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
