# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-25 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_serviceclient_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceclient',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
