# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-04-01 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_serviceclient_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceexpert',
            name='is_olga',
            field=models.NullBooleanField(default=False),
        ),
    ]
