# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-08 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsgate', '0002_auto_20200224_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssettings',
            name='expert_notify',
            field=models.TextField(default=' ', verbose_name='Template expert work notify'),
            preserve_default=False,
        ),
    ]
