# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-07 10:00
from __future__ import unicode_literals

from django.db import migrations
import schoolpub.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schoolpub', '0002_schoollandingpage_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollandingpage',
            name='feedback',
            field=wagtail.core.fields.StreamField([('video', wagtail.core.blocks.ListBlock(schoolpub.models.FeedBackVideo, template='blocks/feedbackvideo_list.html'))], blank=True, null=True),
        ),
    ]
