# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-14 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolpub', '0004_schoolfaqpage_schooltextreviewspage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooltextreviewspage',
            old_name='feedbackReview',
            new_name='review',
        ),
    ]
