# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-01-11 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolpub', '0006_auto_20210111_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoollandingpage',
            name='link_all',
            field=models.URLField(default='/schoolp/apply/', verbose_name='Ссылка на все открытые потоки'),
        ),
    ]
