# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-07 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAppFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAppForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(max_length=40)),
                ('bid', models.DateField()),
                ('accepted', models.CharField(max_length=40)),
                ('payed_by', models.CharField(blank=True, max_length=240, null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolform.SchoolAppFlow')),
            ],
        ),
    ]
