# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-23 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190823_1203'),
        ('schoolform', '0004_schoolappform_instagramm'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolappflow',
            name='education_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolappflow',
            name='education_stop',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolappflow',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=30000, null=True),
        ),
        migrations.AddField(
            model_name='schoolappflow',
            name='recruitment_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolappflow',
            name='recruitment_stop',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolappflow',
            name='toss',
            field=models.ManyToManyField(blank=True, null=True, to='blog.TermsOfServicePage'),
        ),
    ]
