# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-24 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190823_1203'),
        ('schoolform', '0005_auto_20190923_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolappform',
            name='accepted_toss',
            field=models.ManyToManyField(to='blog.TermsOfServicePage'),
        ),
    ]
