# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-30 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinkoff_merchant', '0001_initial'),
        ('schoolform', '0006_schoolappform_accepted_toss'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolappform',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='django_tinkoff_merchant.Payment', verbose_name='Payment'),
        ),
    ]
