# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-10 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0008_auto_20191005_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolappform',
            name='payed_outline',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
