# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-10 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0009_schoolappform_payed_outline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolappform',
            name='payed_outline',
        ),
    ]
