# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-15 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0010_remove_schoolappform_payed_outline'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolappform',
            name='payed_outline',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
