# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-25 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_servicepage_short_descr'),
        ('schoolform', '0011_schoolappform_payed_outline'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAppCurator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(max_length=40)),
                ('instagramm', models.CharField(max_length=80)),
                ('bid', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accepted_toss', models.ManyToManyField(to='blog.TermsOfServicePage')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAppWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(max_length=40)),
                ('instagramm', models.CharField(max_length=80)),
                ('bid', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expert', models.NullBooleanField()),
                ('curator', models.NullBooleanField()),
                ('accepted_toss', models.ManyToManyField(to='blog.TermsOfServicePage')),
            ],
        ),
        migrations.AlterField(
            model_name='schoolappflow',
            name='toss',
            field=models.ManyToManyField(blank=True, null=True, related_name='_schoolappflow_toss_+', to='blog.TermsOfServicePage'),
        ),
        migrations.AddField(
            model_name='schoolappworker',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolform.SchoolAppFlow'),
        ),
        migrations.AddField(
            model_name='schoolappcurator',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolform.SchoolAppFlow'),
        ),
    ]
