# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-25 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_servicepage_short_descr'),
        ('schoolform', '0012_auto_20191025_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolappflow',
            name='cur_toss',
            field=models.ManyToManyField(blank=True, null=True, related_name='_schoolappflow_cur_toss_+', to='blog.TermsOfServicePage'),
        ),
    ]
