# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-25 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0013_schoolappflow_cur_toss'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolappcurator',
            name='curator',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='schoolappcurator',
            name='expert',
            field=models.NullBooleanField(),
        ),
    ]
