# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-25 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_servicepage_short_descr'),
        ('schoolform', '0014_auto_20191025_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolappflow',
            name='pers_cur_price',
            field=models.PositiveIntegerField(default=15000),
        ),
        migrations.AddField(
            model_name='schoolappflow',
            name='pers_cur_toss',
            field=models.ManyToManyField(blank=True, null=True, related_name='_schoolappflow_pers_cur_toss_+', to='blog.TermsOfServicePage'),
        ),
    ]
