# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-25 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0016_schoolappperscuratorform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolappperscuratorform',
            name='bid',
            field=models.DateField(null=True),
        ),
    ]
