# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-22 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0019_schoolappform_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='RUB', max_length=7)),
                ('discount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='schoolappflow',
            name='avail_by_code',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolappflow',
            name='by_code_hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolappform',
            name='price_f',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolform.PriceField'),
        ),
    ]
