# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-25 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0021_schoolappform_pay_url_sended'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolappform',
            name='payed_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
