# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-23 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0022_schoolappform_payed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolappform',
            name='phone_valid',
            field=models.NullBooleanField(default=False),
        ),
    ]
