# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-29 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0023_schoolappform_phone_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolappform',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
