# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-24 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0024_schoolappform_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolappflow',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
