# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-24 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0025_schoolappflow_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolappflow',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
