# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-04-26 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0026_auto_20200324_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolappflow',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
