# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-23 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0027_schoolappflow_is_hidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolappperscuratorform',
            old_name='bid',
            new_name='_bid',
        ),
        migrations.RenameField(
            model_name='schoolappperscuratorform',
            old_name='email',
            new_name='_email',
        ),
        migrations.RenameField(
            model_name='schoolappperscuratorform',
            old_name='first_name',
            new_name='_first_name',
        ),
        migrations.RenameField(
            model_name='schoolappperscuratorform',
            old_name='last_name',
            new_name='_last_name',
        ),
        migrations.RenameField(
            model_name='schoolappperscuratorform',
            old_name='middle_name',
            new_name='_middle_name',
        ),
        migrations.RenameField(
            model_name='schoolappperscuratorform',
            old_name='phone',
            new_name='_phone',
        ),
    ]
