# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-23 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0028_auto_20200523_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolappcurator',
            old_name='bid',
            new_name='_bid',
        ),
        migrations.RenameField(
            model_name='schoolappcurator',
            old_name='email',
            new_name='_email',
        ),
        migrations.RenameField(
            model_name='schoolappcurator',
            old_name='first_name',
            new_name='_first_name',
        ),
        migrations.RenameField(
            model_name='schoolappcurator',
            old_name='instagramm',
            new_name='_instagramm',
        ),
        migrations.RenameField(
            model_name='schoolappcurator',
            old_name='last_name',
            new_name='_last_name',
        ),
        migrations.RenameField(
            model_name='schoolappcurator',
            old_name='middle_name',
            new_name='_middle_name',
        ),
        migrations.RenameField(
            model_name='schoolappcurator',
            old_name='phone',
            new_name='_phone',
        ),
        migrations.RenameField(
            model_name='schoolappform',
            old_name='bid',
            new_name='_bid',
        ),
        migrations.RenameField(
            model_name='schoolappform',
            old_name='email',
            new_name='_email',
        ),
        migrations.RenameField(
            model_name='schoolappform',
            old_name='first_name',
            new_name='_first_name',
        ),
        migrations.RenameField(
            model_name='schoolappform',
            old_name='instagramm',
            new_name='_instagram',
        ),
        migrations.RenameField(
            model_name='schoolappform',
            old_name='last_name',
            new_name='_last_name',
        ),
        migrations.RenameField(
            model_name='schoolappform',
            old_name='middle_name',
            new_name='_middle_name',
        ),
        migrations.RenameField(
            model_name='schoolappform',
            old_name='phone',
            new_name='_phone',
        ),
        migrations.RenameField(
            model_name='schoolappform',
            old_name='phone_valid',
            new_name='_phone_valid',
        ),
        migrations.AddField(
            model_name='schoolappform',
            name='_email_valid',
            field=models.NullBooleanField(default=False),
        ),
    ]
