# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-23 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0031_auto_20200523_1958'),
    ]

    operations = [
    ]
