# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-23 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0032_auto_20200523_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolappcurator',
            name='_bid',
        ),
        migrations.RemoveField(
            model_name='schoolappcurator',
            name='_email',
        ),
        migrations.RemoveField(
            model_name='schoolappcurator',
            name='_first_name',
        ),
        migrations.RemoveField(
            model_name='schoolappcurator',
            name='_instagram',
        ),
        migrations.RemoveField(
            model_name='schoolappcurator',
            name='_last_name',
        ),
        migrations.RemoveField(
            model_name='schoolappcurator',
            name='_middle_name',
        ),
        migrations.RemoveField(
            model_name='schoolappcurator',
            name='_phone',
        ),
        migrations.RemoveField(
            model_name='schoolappform',
            name='_bid',
        ),
        migrations.RemoveField(
            model_name='schoolappform',
            name='_email',
        ),
        migrations.RemoveField(
            model_name='schoolappform',
            name='_email_valid',
        ),
        migrations.RemoveField(
            model_name='schoolappform',
            name='_first_name',
        ),
        migrations.RemoveField(
            model_name='schoolappform',
            name='_instagram',
        ),
        migrations.RemoveField(
            model_name='schoolappform',
            name='_last_name',
        ),
        migrations.RemoveField(
            model_name='schoolappform',
            name='_middle_name',
        ),
        migrations.RemoveField(
            model_name='schoolappform',
            name='_phone',
        ),
        migrations.RemoveField(
            model_name='schoolappform',
            name='_phone_valid',
        ),
        migrations.RemoveField(
            model_name='schoolappperscuratorform',
            name='_bid',
        ),
        migrations.RemoveField(
            model_name='schoolappperscuratorform',
            name='_email',
        ),
        migrations.RemoveField(
            model_name='schoolappperscuratorform',
            name='_first_name',
        ),
        migrations.RemoveField(
            model_name='schoolappperscuratorform',
            name='_last_name',
        ),
        migrations.RemoveField(
            model_name='schoolappperscuratorform',
            name='_middle_name',
        ),
        migrations.RemoveField(
            model_name='schoolappperscuratorform',
            name='_phone',
        ),
    ]
