# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-26 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0033_auto_20200523_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolappperscuratorform',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
