# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-31 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0035_set_curator_rpice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveIntegerField(default=0)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolform.SchoolAppFlow')),
            ],
        ),
        migrations.AddField(
            model_name='schoolappflow',
            name='discounts_by_orders',
            field=models.ManyToManyField(blank=True, related_name='main_flow', to='schoolform.SchoolDiscount'),
        ),
    ]
