# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-01 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinkoff_merchant', '0005_tinkoffsettings_name'),
        ('schoolform', '0036_auto_20200731_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolappflow',
            name='terminal',
            field=models.ManyToManyField(blank=True, related_name='_schoolappflow_terminal_+', to='django_tinkoff_merchant.TinkoffSettings'),
        ),
    ]
