# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-08-07 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0037_schoolappflow_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolappflow',
            name='program_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
