# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-23 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0038_schoolappflow_program_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolScanFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('file', private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='schoolorders/', verbose_name='File')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to='schoolform.SchoolAppForm')),
            ],
        ),
    ]
