# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-30 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0039_schoolscanfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolappform',
            name='access_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
