# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-30 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_tinkoff_merchant', '0005_tinkoffsettings_name'),
        ('schoolform', '0040_schoolappform_access_till'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolExtendAccessService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extends', to='schoolform.SchoolAppForm')),
                ('payment', models.ManyToManyField(blank=True, null=True, to='django_tinkoff_merchant.Payment', verbose_name='Payment')),
            ],
        ),
    ]
