# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-30 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0041_schoolextendaccessservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolextendaccessservice',
            name='access_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolextendaccessservice',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
