# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-30 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0042_auto_20201230_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolappflow',
            name='extend_price',
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
