# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-31 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0043_schoolappflow_extend_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolextendaccessservice',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
