# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-02-28 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0047_schoolappflow_getcourse_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolappflow',
            name='getcourse_ext_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
