# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-04-30 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolform', '0048_schoolappflow_getcourse_ext_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
